### ISSUE TITLE
there is an error when I "Configuring and building libORB_SLAM2_PointMap_SegNetM.so ..."

### ISSUE THREAD

**Issue by jianbozhanghit** [ivipsourcecode/DS-SLAM#1]
/home/dasong/DS_catkin_ws/src/DS-SLAM/src/System.cc: In constructor ‘ORB_SLAM2::System::System(const string&, const string&, const string&, const string&, const string&, ORB_SLAM2::System::eSensor, ORB_SLAM2::Viewer*, ORB_SLAM2::Map*, ORB_SLAM2::ORBVocabulary*)’:
/home/dasong/DS_catkin_ws/src/DS-SLAM/src/System.cc:114:38: error: ‘ORB_SLAM2::ORBVocabulary’ has no member named ‘loadFromBinaryFile’
             bVocLoad = mpVocabulary->loadFromBinaryFile(strVocFile);
                                      ^
make[2]: *** [CMakeFiles/ORB_SLAM2_PointMap_SegNetM.dir/src/System.cc.o] 错误 1
make[1]: *** [CMakeFiles/ORB_SLAM2_PointMap_SegNetM.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by jianbozhanghit** [comment]
median tracking time: 6.08592
mean tracking time: 6.17377
mean orb extract time =0.0314097
mean moving detection time =0.114223
mean segmentation time =6.14007

Saving camera trajectory to CameraTrajectory.txt ...

trajectory saved!

Saving keyframe trajectory to KeyFrameTrajectory.txt ...

trajectory saved!
[TUM-1] process has finished cleanly

**Comment by jsdd25** [comment]
@jianbozhanghit Hello! I have encountered the same problem as the following lines. How did you fix it? Thank you very much!
/home/jin/catkin_ws/src/DS-SLAM/src/System.cc:114:38: error: ‘ORB_SLAM2::ORBVocabulary {aka class DBoW2::TemplatedVocabulary<cv::Mat, DBoW2::FORB>}’ has no member named ‘loadFromBinaryFile’
             bVocLoad = mpVocabulary->loadFromBinaryFile(strVocFile);

**Comment by jianbozhanghit** [comment]
@jsdd25 The Thirdparty/DBoW2 leads to the problem, and you can download another Bow2 to replace it. The version in https://github.com/guiyuliu/orb_slam2_paopao.git is useful.

**Comment by calmelo** [comment]
> median tracking time: 6.08592 mean tracking time: 6.17377 mean orb extract time =0.0314097 mean moving detection time =0.114223 mean segmentation time =6.14007
> 
> Saving camera trajectory to CameraTrajectory.txt ...
> 
> trajectory saved!
> 
> Saving keyframe trajectory to KeyFrameTrajectory.txt ...
> 
> trajectory saved! [TUM-1] process has finished cleanly

I can't find the CameraTrajectory.txt and KeyFrameTrajectory.txt too. Have you resolved it?

**Comment by calmelo** [comment]
> > median tracking time: 6.08592 mean tracking time: 6.17377 mean orb extract time =0.0314097 mean moving detection time =0.114223 mean segmentation time =6.14007
> > Saving camera trajectory to CameraTrajectory.txt ...
> > trajectory saved!
> > Saving keyframe trajectory to KeyFrameTrajectory.txt ...
> > trajectory saved! [TUM-1] process has finished cleanly
> 
> I can't find the CameraTrajectory.txt and KeyFrameTrajectory.txt too. Have you resolved it?

I resolve this by using absolute path.
