### ISSUE TITLE
Questions about showing result

### ISSUE THREAD

**Issue by yubaoliu** [ivipsourcecode/DS-SLAM#14]
I'm trying to run 
` roslaunch DS_SLAM_TUM.launch`
using rgbd_dataset_freiburg3_walking_xyz dataset

I got this result:
![image](https://user-images.githubusercontent.com/17697584/59960972-9f38f600-950b-11e9-9fb5-429d93e93a5b.png)
![image](https://user-images.githubusercontent.com/17697584/59960982-d5767580-950b-11e9-889a-10458a459ed2.png)
`$ rostopic list
/Camera_Odom
/Camera_Pose
/ORB_SLAM2_PointMap_SegNetM/Point_Clouds
/clicked_point
/free_cells_vis_array
/initialpose
/move_base_simple/goal
/occupied_cells_vis_array
/octomap_binary
/octomap_full
/octomap_point_cloud_centers
/octomap_server/parameter_descriptions
/octomap_server/parameter_updates
/odom
/point_cloud
/projected_map
/rosout
/rosout_agg
/tf
/tf_static
`

`Wait for new RGB img time =
process time =16.7728
wait for new segment img time  =0.000384
check time =0.039342
SLAM TrackRGBD all time =45.6625

Wait for new RGB img time =
process time =15.2025
wait for new segment img time  =0.000377
check time =0.045316
SLAM TrackRGBD all time =49.9497

-------
`

Then, I have some questions:
1. How can I check RGB images?
2. How can I check the segmentation result or the result after outlier removed by RGB images in real time?
3. How can I use the kinetic v2 camera or realsense camera to run it in real time? Is there any sample code?

Thanks

**Comment by yubaoliu** [comment]
[supplement]:
![image](https://user-images.githubusercontent.com/17697584/59961283-9f87c000-9510-11e9-8c49-fdbf2ad83e58.png)
That is how can I check the result shown in the above image: 
1. 'Semantic octo-tree map'
2. 'Remove outliers'
Thanks

**Comment by yubaoliu** [comment]
That is how can I check the result shown in the above image:
![image](https://user-images.githubusercontent.com/17697584/59961312-e970a600-9510-11e9-905f-1521184a077c.png)

'Semantic octo-tree map'
'Remove outliers'
Thanks

**Comment by yubaoliu** [comment]
Solved

Thanks

**Comment by Dongdong-NEU** [comment]
> Solved
> 
> Thanks

您好，请问您实现了在线接入相机实时运行了吗？我现在只可以用azure录个rosbag 转成TUM数据集格式使用这个算法😂
