### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by CoffinIan** [ivipsourcecode/DS-SLAM#18]
your work is excellent，thanks for your code sharing.But I compile it using a long time,at last,it still has errors and can not compile successfully. My computer is i7CPU,not has GPU,I install caffe with CPU only(I don't know whether GPU and CUDA are necessary for this work.)
I install octomap and octomap_rviz in my ros workspace(catkin_ws/src),and I put the caffe-segnet-cudnn5 in /home/DS-SLAM/Examples/ROS/ORB_SLAM2_PointMap_SegNetM.
when I run ./DS_SLAM_BUILD.sh,Error is as follows
![2019-10-10 16-25-22屏幕截图](https://user-images.githubusercontent.com/49222681/66552104-591ba700-eb7b-11e9-9122-564efb060647.png)

**Comment by romiparada** [comment]
Were you able to run in CPU mode?
