### ISSUE TITLE
when I have finshed this DS-SLAM, I can't find the result "CameraTrajectory.txt" and "KeyFrameTrajectory.txt"

### ISSUE THREAD

**Issue by jianbozhanghit** [ivipsourcecode/DS-SLAM#2]
median tracking time: 6.08592
mean tracking time: 6.17377
mean orb extract time =0.0314097
mean moving detection time =0.114223
mean segmentation time =6.14007

Saving camera trajectory to CameraTrajectory.txt ...

trajectory saved!

Saving keyframe trajectory to KeyFrameTrajectory.txt ...

trajectory saved!

**Comment by calmelo** [comment]
> median tracking time: 6.08592 mean tracking time: 6.17377 mean orb extract time =0.0314097 mean moving detection time =0.114223 mean segmentation time =6.14007
> 
> Saving camera trajectory to CameraTrajectory.txt ...
> 
> trajectory saved!
> 
> Saving keyframe trajectory to KeyFrameTrajectory.txt ...
> 
> trajectory saved!

Have you resolved the problem? I can't find the CameraTrajectory.txt and KeyFrameTrajectory.txt too.

**Comment by calmelo** [comment]
> > median tracking time: 6.08592 mean tracking time: 6.17377 mean orb extract time =0.0314097 mean moving detection time =0.114223 mean segmentation time =6.14007
> > Saving camera trajectory to CameraTrajectory.txt ...
> > trajectory saved!
> > Saving keyframe trajectory to KeyFrameTrajectory.txt ...
> > trajectory saved!
> 
> Have you resolved the problem? I can't find the CameraTrajectory.txt and KeyFrameTrajectory.txt too.

I resolve this by using absolute path.

**Comment by Sujan-PhdWork** [comment]
check in ~/.ros
